stages:
  - build

._build: &_build
  services:
    - name: docker:dind
      command: [--experimental]
  stage: build
  before_script:   
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  tags:     
    - dind
build_tag:
  <<: *_build
  only:
    - /^\d+$/
  script:
    - docker image build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --squash --compress --no-cache --rm --pull .
    - docker image push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
build_latest:
  <<: *_build
  only: 
    - master
  script:
    - docker image build -t $CI_REGISTRY_IMAGE:latest --squash --compress --no-cache --rm --pull .
    - docker image push $CI_REGISTRY_IMAGE:latest
